### PR TITLE
[#4919] Chevah-related fixes in cryptography 2.2.2.

### PR DESCRIPTION
**Pull request by dumol**
Documented the changes in our `chevah`, `chevah2` and `chevah3` tarballs from http://pypi.chevah.com.

I'll try to upstream changes in `chevah` and `chevah3` in some form or another…

@adiroiban, just a FYI.

### CODE REVIEW

**Comment by dumol** [comment]
Trying to upstream HP-UX related changes at https://github.com/pyca/cryptography/pull/4259.

For Solaris, I'm not sure, we are not actually testing the change, as we are on 11.2, where we use pristine `cryptography` version 1.8.2.

The OpenBSD-related changes were lifted from upstream, should make their way in 2.2.3.

**Comment by adiroiban** [comment]
Thanks. What I would like to see is a 2.2.x-chevah branch and when we push in production a python-package using any 2.2.x.chevahX version there is a commit with the version number in the message...or a tag for it.

**Comment by dumol** [comment]
Thanks, I'll keep this in mind next time. For current changes there is not going to be a need for this, as our changes are being accepted at https://github.com/pyca/cryptography/pull/4259.

**Review by adiroiban — CHANGES_REQUESTED** [review]
Thanks.

I don't see these changes upstream

```
src/_cffi_src/openssl/x509.py
src/_cffi_src/openssl/x509_vfy.py
```
So is not clear why we would no longer need this code?
Thanks!

**Comment by dumol** [comment]
Those are the OpenBSD-related fixes, they were lifted from upstream, bound to be included in the next stable version of `cryptography`.

**Review by adiroiban — APPROVED** [review]
Thanks.

Just a suggestion,
For openbsd changes a commit message like "Backport (or apply) upstream unreleased changes for OpenBSD 6.3 support" would help understand that the changes were already presetnt upstream but we are using them for an older version. .. are an unrelease version

**Comment by dumol** [comment]
No longer relevant.

**Pull request closed without merging**
